default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['USERNAME_DB'] %>
  password: <%= ENV['PASSWORD_DB'] %>

development:
  <<: *default
  database: bowling_api_development

test:
  <<: *default
  database: bowling_api_test

production:
  <<: *default
  database: bowling_api_production
